.PHONY: help check init plan clean apply fmt

export AWS_REGION
export S3_BUCKET
export DIRECTORY

help:
	@cat $(firstword $(MAKEFILE_LIST))

check:
	type tfenv

init: state.config
	terraform init -backend-config="$<"

plan: \
	tfplan

clean:
	-rm tfplan

apply:
	terraform apply tfplan

fmt:
	terraform fmt

tfplan:
	terraform plan -out $@

state.config: state.template.config
	export COMMENT="This file was generated by Makefile" && envsubst < $< > $@

.auto.tfvars.json:
	jq -n -r '{s3_codepipeline_artifact_arn, github_repository, slack_team_name, slack_channel_id}' > $@
